[package]
name = "rust-pool-stats"
version = "0.1.0"
edition = "2024"

[dependencies]
alloy = { version = "0.12.6", features = ["full"] }
log = "0.4"
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
reqwest = "0.11"
once_cell = "1.21.1"
